apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hms-client
spec:
  destination:
    namespace: hms
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/production/hms-client
    repoURL: 'https://github.com/org-ofirdassa9/devops-project-infra.git'
    targetRevision: master
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true