apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: report-generator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/org-ofirdassa9/devops-project-infra.git'
    path: argocd/production/report-generator
    targetRevision: HEAD
  destination:
    namespace: hms
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
