apiVersion: v1
data:
  access-key: <aws-access-key-id>
  secret: <aws-secret-key>
kind: Secret
metadata:
  name: aws-creds
  namespace: hms
type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: production-secret-store
  namespace: hms
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        secretRef:
          accessKeyIDSecretRef: 
            name: aws-creds
            key: access-key
          secretAccessKeySecretRef:
            name: aws-creds
            key: secret-access