apiVersion: v1
data:
  access-key: <aws-access-key-id>
  secret: <aws-secret-key>
kind: Secret
metadata:
  name: aws-secret
  namespace: hms
type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: production-secret-store
  namespace: hms
spec:
  provider:
    aws:  # set secretStore provider to AWS.
      service: SecretsManager # Configure service to be Secrets Manager
      region: eu-west-1   # Region where the secret is.
      auth:
        secretRef:
          accessKeyIDSecretRef: 
            name: aws-secret # References the secret we created
            key: access-key
          secretAccessKeySecretRef:
            name: aws-secret
            key: secret