apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      serviceAccountName: sa-users-service
      containers:
      - name: users-service
        image: 476209828715.dkr.ecr.eu-west-1.amazonaws.com/org-ofirdassa9_devops-project-server:users-service-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PROJECT_NAME
          valueFrom:
            secretKeyRef:
              name: secret-users-service
              key: PROJECT_NAME
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-users-service
              key: JWT_SECRET_KEY
        - name: DB_CONN_STRING
          valueFrom:
            secretKeyRef:
              name: secret-users-service
              key: DB_CONN_STRING
      initContainers:
        - name: "users-service-init"
          image: "476209828715.dkr.ecr.eu-west-1.amazonaws.com/org-ofirdassa9_devops-project-server:init-latest"
          imagePullPolicy: Always
          env:
          - name: DB_CONN_STRING
            valueFrom:
              secretKeyRef:
                name: secret-users-service
                key: DB_CONN_STRING
