apiVersion: v1
kind: Secret
metadata:
  name: secret-users-service
type: Opaque
data:
  PROJECT_NAME: "Users Service"
  JWT_SECRET_KEY: "your-secret-key"
  DB_CONN_STRING: "postgresql://hmsuser:GVx.4eYvaes<kVkOSx84gGbfQ53.@rds-production-postgres.ckj1jt1pdnnn.eu-west-1.rds.amazonaws.com/hms"
  