apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: tgb-users-service
spec:
  serviceRef:
    name: svc-users-service
    port: 80
  targetGroupARN: "arn:aws:elasticloadbalancing:eu-west-1:476209828715:targetgroup/tg-production-users-service/a5c85231e110395b"
