version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/tf-modules"
    schedule:
      interval: "weekly"
    labels:
      - "terraform"

  - package-ecosystem: "terraform"
    directory: "/terragrunt"
    schedule:
      interval: "weekly"
    labels:
      - "terraform"

  - package-ecosystem: "docker"
    directory: "/kube-files"
    schedule:
      interval: "weekly"
    labels:
      - "kubernetes"
      
  - package-ecosystem: "docker"
    directory: "/charts"
    schedule:
      interval: "weekly"
    labels:
      - "kubernetes"
