apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: report-generator-external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: production-secret-store #The secret store name we have just created.
    kind: SecretStore
  target:
    name: secret-report-generator # Secret name in k8s
  data:
  - secretKey: PROJECT_NAME
    remoteRef:
      key: "/eks/production/report-generator"
      property: PROJECT_NAME
  - secretKey: JWT_SECRET_KEY
    remoteRef:
      key: "/eks/production/report-generator"
      property: JWT_SECRET_KEY
  - secretKey: DB_CONN_STRING
    remoteRef:
      key: "/eks/production/report-generator"
      property: DB_CONN_STRING