apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hms-client
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/hms-client
    repoURL: 'https://github.com/org-ofirdassa9/devops-project-infra.git'
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
