apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-client
  labels:
    app: hms-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hms-client
  template:
    metadata:
      labels:
        app: hms-client
    spec:
      # serviceAccountName: sa-hms-client
      containers:
      - name: hms-client
        image: 476209828715.dkr.ecr.eu-west-1.amazonaws.com/org-ofirdassa9_devops-project-client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        