apiVersion: v1
kind: Service
metadata:
  name: svc-hms-client
  labels:
    app: hms-client
    tier: frontend
spec:
  selector:
    app: hms-client
    tier: frontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
