apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: tgb-hms-client
spec:
  serviceRef:
    name: svc-hms-client
    port: 80
  targetGroupARN: "arn:aws:elasticloadbalancing:eu-west-1:476209828715:targetgroup/tg-production-fallback/d302b94dfa423dbf"
