apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  serviceRef:
    name: prometheus-grafana-kube-pr-alertmanager
    port: 9093
  targetGroupARN: "arn:aws:elasticloadbalancing:eu-west-1:476209828715:targetgroup/tg-production-alert-manager/83075562671387f8"
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: grafana
  namespace: monitoring
spec:
  serviceRef:
    name: prometheus-grafana
    port: 80
  targetGroupARN: "arn:aws:elasticloadbalancing:eu-west-1:476209828715:targetgroup/tg-production-grafana/7c32acfec302454a"
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceRef:
    name: prometheus-grafana-kube-pr-prometheus
    port: 9090
  targetGroupARN: "arn:aws:elasticloadbalancing:eu-west-1:476209828715:targetgroup/tg-production-prometheus/0772237812cc22c0"
