apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-process
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metrics-process
  template:
    metadata:
      labels:
        app: metrics-process
    spec:
      serviceAccountName: sa-metrics-process
      containers:
      - name: metrics-process
        image: 476209828715.dkr.ecr.eu-west-1.amazonaws.com/org-ofirdassa9_devops-project-server:metrics-process-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PROJECT_NAME
          valueFrom:
            secretKeyRef:
              name: secret-metrics-process
              key: PROJECT_NAME
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-metrics-process
              key: JWT_SECRET_KEY
        - name: DB_CONN_STRING
          valueFrom:
            secretKeyRef:
              name: secret-metrics-process
              key: DB_CONN_STRING
