name: push-charts

on:
  push:
    branches:
      - 'master'
      
jobs:
        
  hms-client:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::476209828715:role/role-github-actions
          aws-region: "eu-west-1"
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: prepare ECR repo name based on the Github repository
        shell: bash
        run: |
          set -eux
          # lowercase the name
          repo="${GITHUB_REPOSITORY,,}_${GITHUB_JOB,,}"

          # replace / with _
          echo "REPO_NAME=${repo//\//_}" >> $GITHUB_ENV
          
      - name: Package and push helm chart to Amazon ECR
        shell: bash
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.REPO_NAME }}

        run: |
          cd charts
          helm package hms-client
          VERSION_NUM=$(cat hms-client/Chart.yaml | grep 'version:' | awk '{print $2}')
          echo $REPOSITORY-$VERSION_NUM.tgz
          helm push $REPOSITORY-$VERSION_NUM.tgz oci://$REGISTRY