name: push-charts

on:
  push:
    branches:
      - 'master'

jobs:
        
  hms-client:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::476209828715:role/role-github-actions
          aws-region: "eu-west-1"
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
          
      - name: Package and push helm chart to Amazon ECR
        shell: bash
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}

        run: |
          cd charts
          VERSION_NUM=0.3.${{github.run_number}}
          helm package hms-client --version $VERSION_NUM
          helm push hms-client-$VERSION_NUM.tgz oci://$REGISTRY